Repository HackYourFuture-CPH/rate-my-cv, pull requests merged in 2021-02, with the labels that each got.

#96 new CV Modal is created (removed the buttons and added extra txt)
  src/client/components/AddResume/AddResume.css
  src/client/components/AddResume/AddResume.js
Labels: frontend

#103 patch users controllers and router changes implemented
  src/server/api/controllers/users.controller.js
  src/server/api/routes/users.router.js
Labels: backend

#72 Implement card cv view-search component
  src/client/components/CardCvViewSearchComponent/CardCvViewSearchComponent.js
  src/client/components/CardCvViewSearchComponent/CardCvViewSearchComponent.stories.js
  src/client/components/CardCvViewSearchComponent/CardCvViewSearchComponent.styles.css
Labels: frontend

#77 Footer implemented
  src/client/App.js
  src/client/assets/images/icons/facebook.svg
  src/client/components/Footer/Footer.css
  src/client/components/Footer/Footer.js
  src/client/components/Footer/Footer.stories.js
Labels: frontend

#107 patch cvs and controllers
  src/server/api/controllers/cvs.controller.js
  src/server/api/routes/cvs.router.js
Labels: backend

#124 Cv cardlist search
  src/client/components/CvcardListSearch/CvcardList.js
  src/client/components/CvcardListSearch/CvcardList.stories.js
  src/client/components/CvcardListSearch/CvcardList.styles.css
Labels: frontend

#54 34 uploading file
  src/client/components/SearchComponent/Search.js
  src/client/hooks/fileUploader.js
Labels: frontend

#84 added type and onclick as props
  src/client/components/Button/Button.js
  src/client/components/Button/Button.stories.js
  src/client/components/Button/Button.styles.css
Labels: frontend

#108 post api cvs in cv.controller
  src/server/api/controllers/cvs.controller.js
  src/server/api/routes/cvs.router.js
Labels: backend

#113 postbuild script to db setup
  package.json
Labels: deployment

#110 added profile image url to sign-up container
  src/client/containers/SignUp/index.js
Labels: frontend

#125 fix issues on component with createdDate...
  src/client/assets/images/portraits/unknown-black.png
  src/client/components/CardCvViewSearchComponent/CardCvViewSearchComponent.js
  src/client/components/CardCvViewSearchComponent/CardCvViewSearchComponent.styles.css
Labels: frontend

#111 added storybook build npm script
  .gitignore
  package.json
Labels: deployment

#116 endpoint_to_delete_cv_using_parameter_ID
  src/server/api/controllers/cvs.controller.js
  src/server/api/routes/cvs.router.js
Labels: backend

#106 Created instructions component for home page
  src/client/assets/images/feedback.png
  src/client/assets/images/notification.png
  src/client/assets/images/upload.png
  src/client/components/InstructionsComponent/Instructions.stories.js
  src/client/components/InstructionsComponent/InstructionsComponent.css
  src/client/components/InstructionsComponent/InstructionsComponent.js
Labels: frontend

#105 Header/#31
  src/client/App.js
  src/client/assets/images/icons/user-icon.png
  src/client/components/Navigation/Header.css
  src/client/components/Navigation/Header.js
  src/client/components/Navigation/Header.stories.js
Labels: frontend

#118 no footer for sign-up & sign-in
  src/client/App.js
Labels: frontend

#133 Created Login Form
  src/client/components/LoginForm/LoginForm.css
  src/client/components/LoginForm/LoginForm.js
  src/client/components/LoginForm/LoginForm.stories.js
  src/client/components/LoginForm/Validation.js
  src/client/components/LoginForm/github.png
  src/client/components/LoginForm/useForm.js
Labels: frontend

#127 Cvpdffile/issue83
  src/client/components/CvPdfRender.js
  src/client/components/CvPdfRender.stories.js
  src/server/seeds/development/02_cvs.js
Labels: frontend

#140 Implement coloured component...
  src/client/assets/images/sign-in.png
  src/client/assets/images/sign-up.png
  src/client/components/SideBanner/SideBanner.js
  src/client/components/SideBanner/SideBanner.stories.js
  src/client/components/SideBanner/SideBanner.styles.css
Labels: frontend

#147 added linkedin url
  src/client/components/Footer/Footer.js
Labels: frontend

#131 Signup userform Component with password validation
  src/client/components/Forms/SignUp.js
  src/client/components/Forms/SignUp.stories.js
  src/client/components/Forms/Signup.style.css
  src/client/components/LoginForm/LoginForm.js
  src/client/components/LoginForm/Validation.js
  src/client/components/LoginForm/useForm.js
Labels: frontend

#145 home page slogan developed
  src/client/assets/images/portraits/homeimage.png
  src/client/components/Home/HomepageSlogan.js
  src/client/components/Home/HomepageSlogan.stories.js
  src/client/components/Home/HomepageSlogan.style.css
Labels: frontend

#146 Update package.json & package-lock
  package.json
  webpack.config.js
Labels: bug, frontend, priority

#161 Fix console errors from component...
  src/client/components/ProfileCardComponent/ProfileCardComponent.js
Labels: frontend

#138 Issue#90/input review container
  src/client/components/ReviewPost/ReviewEditorComponent/ReviewEditorComponent.js
  src/client/components/ReviewPost/ReviewEditorComponent/ReviewEditorComponent.stories.js
  src/client/components/ReviewPost/ReviewEditorComponent/ReviewEditorComponent.style.css
Labels: frontend

#155 Endpoint to retrieve the last uploaded CVs #95
  src/client/components/RetrivingCvs/RetrivingCvs.js
  src/server/api/controllers/usercv.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/usercv.router.js
Labels: backend

#156 49 upload new cv using fetch
  src/client/components/AddResume/AddResume.css
  src/client/components/AddResume/AddResume.js
Labels: frontend

#152 Title and Description Component
  src/client/components/Title/TitleDesc.js
  src/client/components/Title/TitleDesc.stories.js
  src/client/components/Title/TitleDesc.styles.css
Labels: frontend

#154 Fix positioning of footer...
  public/index.html
  src/client/components/Footer/Footer.css
  src/client/components/Footer/Footer.js
  src/client/index.css
Labels: enhancement, frontend

#172 Delete file not needed
  src/client/components/RetrivingCvs/RetrivingCvs.js
Labels: frontend

#144 Implement sign-up page
  src/client/containers/SignUp/SignUp.css
  src/client/containers/SignUp/index.js
Labels: frontend

#166 Added side banner in SigIn page
  src/client/components/LoginForm/LoginForm.css
  src/client/containers/SignIn/SignIn.css
  src/client/containers/SignIn/index.js
Labels: frontend

#176 Displays 3 latest uploaded cvs
  src/client/components/CvcardListSearch/CvcardList.js
  src/client/components/CvcardListSearch/CvcardList.stories.js
  src/client/components/CvcardListSearch/CvcardList.styles.css
Labels: frontend

#157 Search Filter Component
  src/client/App.js
  src/client/assets/images/icons/star.svg
  src/client/assets/images/icons/triangle.svg
  src/client/components/SearchFilterComponent/SearchFilter.js
  src/client/components/SearchFilterComponent/SearchFilter.stories.js
  src/client/components/SearchFilterComponent/SearchFilter.styles.css
Labels: frontend, low priority

#191 Fix console errors from missing keys and ...
  src/client/components/MyProfile/YourUploadedCVs/YourUploadedCVs.js
  src/client/components/MyProfile/YourUploadedCVs/YourUploadedCVs.stories.js
Labels: frontend

#190 Fix console errors from missing keys...
  src/client/components/RatingStars/RatingStars.js
Labels: frontend

#162 Added review post for CV review
  src/client/components/ReviewPost/ReviewPost.js
  src/client/components/ReviewPost/ReviewPost.stories.js
  src/client/components/ReviewPost/ReviewPost.styles.css
Labels: frontend

#186 functionality for signIn page
  src/client/components/LoginForm/LoginForm.js
  src/client/components/LoginForm/useForm.js
  src/client/containers/SignIn/SignIn.css
  src/client/containers/SignIn/index.js
Labels: frontend

#173 Post cv fields by user to database
  src/client/components/PostUrl/PostUrlComponent.js
  src/client/hooks/useAuthentication.js
  src/server/api/routes/api-router.js
Labels: backend, frontend

#198 path Footer component imported and tag added in app.js
  src/client/App.js
Labels: frontend

#200 bring back header & footer
  src/client/App.js
Labels: frontend

#188 Retrive user cvs#95
  src/server/api/controllers/usercv.controller.js
  src/server/api/controllers/users.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/usercv.router.js
Labels: backend

#207 users.controller had been deleted by mistake, its back now
  src/server/api/controllers/users.controller.js
Labels: backend

#195 created end points for specific cv and by specific user
  src/server/api/controllers/reviews.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/reviews.router.js
Labels: backend

#168 Implement sent reviews...
  src/client/components/SentReviewsComponent/SentReviewsComponent.js
  src/client/components/SentReviewsComponent/SentReviewsComponent.stories.js
  src/client/components/SentReviewsComponent/SentReviewsComponent.styles.css
Labels: frontend

#205 User sign-out
  src/client/App.js
  src/client/components/Navigation/Header.js
Labels: frontend

#212 moved seperate files into a component
  src/client/components/MyProfile/YourUploadedCVs/CvPdfRender.js
  src/client/components/MyProfile/YourUploadedCVs/CvPdfRender.stories.js
Labels: frontend

#159 Profile Main Page
  src/client/components/MyProfile/ProfilePage/ProfileComponent.js
  src/client/components/MyProfile/ProfilePage/ProfileComponent.styles.css
  src/client/components/ProfileCardComponent/ProfileCardComponent.js
  src/client/containers/Profile/index.js
  src/client/containers/Profile/index.styles.css
  src/client/hooks/useAuthentication.js
Labels: frontend

#219 adding width 100% to sent-reviws component
  src/client/components/MyProfile/ProfilePage/ProfileComponent.styles.css
Labels: frontend

#217 'Fix overwritten Css in sent reviews component'
  src/client/components/SentReviewsComponent/SentReviewsComponent.js
  src/client/components/SentReviewsComponent/SentReviewsComponent.styles.css
Labels: frontend

#201 Homepage
  src/client/assets/images/img-1.png
  src/client/assets/images/img-2.png
  src/client/containers/Home/Home.css
  src/client/containers/Home/Home.js
  src/client/containers/Home/Home.test.js
Labels: frontend

#223 Change names of classes due to overwriting ...
  src/client/components/CardCvViewSearchComponent/CardCvViewSearchComponent.js
  src/client/components/CardCvViewSearchComponent/CardCvViewSearchComponent.styles.css
Labels: frontend

#222 Implement changes on HomepageSlogan component...
  src/client/assets/images/home-slogan.jpg
  src/client/assets/images/portraits/homeimage.png
  src/client/components/Home/HomepageSlogan.js
  src/client/components/Home/HomepageSlogan.style.css
Labels: frontend
